### ISSUE TITLE
Conda error : "FileNotFoundError: [WinError 2] The system cannot find the file specified"

### ISSUE THREAD

**Issue by jeremysintes** [erikrose/sphinx-js#28]
Dear all,

Thanks for this extension which looks amazing.

I think I may have an error related to the fact that I use anaconda. 
If you have any leads to solve it, it would be great!

Thanks in advance,
Jérémy

## Error message
`Running Sphinx v1.6.3
making output directory...
loading pickled environment... not yet created`

`Exception occurred:`
`  File "C:\Users\Jsintes\AppData\Local\conda\conda\envs\test_sphinx-js\lib\subprocess.py", line 957, in  startupinfo)`
`FileNotFoundError: [WinError 2] The system cannot find the file specified`

[sphinx-err-x_hvtdnq.txt](https://github.com/erikrose/sphinx-js/files/1311809/sphinx-err-x_hvtdnq.txt)

## Step to reproduce the error 
First I cloned the fathom project : 
`git clone https://github.com/mozilla/fathom`

Then created a conda env and activated it
`conda create -n sphinx-js`
`activate sphinx-js`

Then I installed the requirements
`npm install -g jsdoc`
`pip install sphinx`
`pip install sphinx-js`

And I tried to build the html from docs
`make html`

That's when the error occurred.

**Comment by erikrose** [comment]
Is `jsdocs` (rather than `jsdoc`) above just a typo?

**Comment by vladbytex** [comment]
Hello, 

I have a similar problem but on Ubuntu 17.04. When I try to run `make html` i get the following error:

`Sphinx version: 1.6.4
Python version: 2.7.13 (CPython)
Docutils version: 0.14 
Jinja2 version: 2.9.6
Last messages:

Loaded extensions:
Traceback (most recent call last):
  File "/home/vlad/.local/lib/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/vlad/.local/lib/python2.7/site-packages/sphinx/application.py", line 234, in __init__
    self._init_builder()
  File "/home/vlad/.local/lib/python2.7/site-packages/sphinx/application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "/home/vlad/.local/lib/python2.7/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/home/vlad/.local/lib/python2.7/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/vlad/.local/lib/python2.7/site-packages/sphinx_js/jsdoc.py", line 31, in run_jsdoc
    p = Popen(jsdoc_command, stdout=temp, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by erikrose** [comment]
I bet 692ee1487d4f36d0d2ffe303fb70a829cb5c5c60 fixes this: it was looking for "jsdoc" to run, but in Windows it's called "jsdoc.cmd". If not, please reopen.
