### ISSUE TITLE
Error building on readthedocs

### ISSUE THREAD

**Issue by dselman** [erikrose/sphinx-js#35]
The error message is below. My interpretation of this is that it is failing because the `jsdoc` npm module is not globally installed. How do you configure readthedocs to install jsdoc into the build environment?

My project is here:
https://github.com/accordproject/cicero

```
Running Sphinx v1.5.6
making output directory...
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/accordcicero/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/accordcicero/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 244, in __init__
    self._init_builder(self.buildername)
  File "/home/docs/checkouts/readthedocs.org/user_builds/accordcicero/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 315, in _init_builder
    self.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/accordcicero/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 589, in emit
    results.append(callback(self, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/accordcicero/envs/latest/local/lib/python2.7/site-packages/sphinx_js/jsdoc.py", line 31, in run_jsdoc
    p = Popen(jsdoc_command, stdout=temp, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Exception occurred:
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
The full traceback has been saved in /tmp/sphinx-err-Qkh_St.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by dselman** [comment]
So, it seems like jsdoc is installed:
https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile#L49

**Comment by dselman** [comment]
Still can't get this to work. Even, when not setting `js_source_path` or `jsdoc_config_path`. It looks like the Popen for `jsdoc` is failing...
https://github.com/erikrose/sphinx-js/blob/master/sphinx_js/jsdoc.py#L31

@erikrose do you have any ideas? Do I need to drop `readthedocs` as the build system and switch to Travis and GitHub pages (like the Fathom example)?

**Comment by skddc** [comment]
I had to have them manually flip a switch on my project, then wipe the builds and rebuild, and since then it's working. See https://github.com/rtfd/readthedocs.org/issues/3069 (and maybe add a comment there that's it's still not working for new projects).

**Comment by erikrose** [comment]
Ugh, I'm sorry, all; I thought RTD was all ready to go. Turns out it's still in a sort of opt-in beta; I'll update my docs.
