### ISSUE TITLE
Rule 'path' didn't match at '../docs/interfaces/a'

### ISSUE THREAD

**Issue by Towerism** [erikrose/sphinx-js#72]
I am using typedoc.

Here is the full traceback:
```
# Sphinx version: 1.7.9
# Python version: 2.7.14 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\sphinx\cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "c:\python27\lib\site-packages\sphinx\application.py", line 233, in __init__
    self._init_builder()
  File "c:\python27\lib\site-packages\sphinx\application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "c:\python27\lib\site-packages\sphinx\application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "c:\python27\lib\site-packages\sphinx\events.py", line 79, in emit
    results.append(callback(*args))
  File "c:\python27\lib\site-packages\sphinx_js\doclets.py", line 44, in gather_doclets
    doclet_full_path(d, root_for_relative_paths),
  File "c:\python27\lib\site-packages\sphinx_js\doclets.py", line 189, in doclet_full_path
    path_and_formal_params['path'].parse(path))
  File "c:\python27\lib\site-packages\parsimonious\expressions.py", line 110, in parse
    node = self.match(text, pos=pos)
  File "c:\python27\lib\site-packages\parsimonious\expressions.py", line 127, in match
    raise error
ParseError: Rule 'path' didn't match at '../docs/interfaces/a' (line 1, column 1).
```

**Comment by Towerism** [comment]
Solved it by changing `conf.py`.

I changed it from 

```
js_language = 'typescript'
js_source_path = '../src'
jsdoc_config_path = '../tsconfig.json'
root_for_relative_js_paths = '..'
```

to 

```
js_language = 'typescript'
js_source_path = '../src'
jsdoc_config_path = '../tsconfig.json'
root_for_relative_js_paths = '..'
```

**Comment by yanickdi** [comment]
Thanks! I'm having the same issue here and  
`root_for_relative_js_paths = '..'`
works.

Using:
TypeDoc 0.14.2
Sphinx-js 2.7.1
Sphinx v1.8.5
Typescript v1.8.5

Seems like no matter if your js_source_path is a child/sibling/etc. of the sphinx directory - you always have to set the root_for_relative_js_path to '..'

I suggest to reopen this Issue?
